### ISSUE TITLE
Choosing dialogue options with number keys doesn't work with the plugin enabled

### ISSUE THREAD

**Issue by TomBtw** [WhatATopic/Shift-Remapping#3]
Pressing the number keys (eg. 1-5) to choose options while having that key rebound to shift (mine is 3) does not work.

Example:
![image](https://github.com/user-attachments/assets/55d74053-e3ce-4d95-b386-4adb1fad4668)

**Comment by TomBtw** [comment]
This problem also exists with runelite's own key remapping plugin, I found a relevant issue https://github.com/runelite/runelite/issues/16274

**Comment by WhatATopic** [comment]
I've known about this issue but was too lazy to fix so thanks for giving me the push. Once my updates are reviewed and accepted, there will be a config option to disable shift remapping when the dialog option menu is open or when the bank pin interface is open. By default, it will be enabled. 

Also that relevant issue you linked is the opposite of the problem you are experiencing. They want remapping to work when dialog option menus are open while you do not want it to work. Due to that, I decided to make it a config option so everyone is happy!

**Comment by TomBtw** [comment]
Oh, I must have misread. Thanks though! Is there a chance to get this fix to work with the other plugin? Runelite's own plugin still has this issue too

**Comment by WhatATopic** [comment]
It can easily be done but the Runelite devs will have to change it and who knows if they care enough to. From what I can tell, they only check to make sure a dialog box isn't open for remapping f keys and escape. They didn't do it for control remapping. They also only do space remapping when a dialog box (click here to continue) is open and unfortunately their method also encompasses the bank pin interface so if you have a number key as space then you can't use it to enter bank pin.

**Comment by TomBtw** [comment]
Yeah that sucks. Is there any way to include the rebinding of control in this plugin?
